name: Go

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get Swag binary
      run: wget https://github.com/swaggo/swag/releases/download/v1.7.1/swag_linux_amd64.tar.gz -O - | tar -xz -C /tmp && cp /tmp/swag_linux_amd64/swag /usr/local/bin

    - name: Generate Swagger doc
      run: make docs
      
    - name: Change directory
      run: |
        cd docs
        curl -X POST -H "Content-Type: application/json" -d "@swagger.json" https://converter.swagger.io/api/convert -o openapi.json
        export SCHEMA=$(jq -Rs '.' openapi.json)
        echo $SCHEMA
        curl -v -X PUT https://api.getpostman.com/apis/b54513bd-a2dd-4da2-b3a8-cb52db966425/versions/b27cffa3-c21d-4af4-a9ce-14d8eeaad83d/schemas/1da92d5f-18e2-4ca6-8344-2af2a9bb680c \
        --header 'Content-Type: application/json' \
        --header 'X-API-Key: ${{ secrets.POSTMAN_API_KEY}}' \
        --data-raw '{"schema": {"language": "json", "schema": '"$SCHEMA"', "type": "openapi3"}}'
